services:
  datadog.event_subscriber.audit:
    class: DataDog\AuditBundle\EventSubscriber\AuditSubscriber
    arguments: [@security.token_storage]
    tags:
      - { name: doctrine.event_subscriber, connection: default }
