app:
  resource: "@AppBundle/Controller/"
  type:     annotation

login_check:
  path: /login_check

logout:
  path: /logout

_wdt:
  resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
  prefix:   /_wdt

_profiler:
  resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
  prefix:   /_profiler

_errors:
  resource: "@TwigBundle/Resources/config/routing/errors.xml"
  prefix:   /_error
