security:
  encoders:
    AppBundle\Entity\User:
      algorithm: bcrypt

  providers:
    user_db_provider:
      entity:
        class: AppBundle:User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt|error)|css|images|js)/
      security: false
    default:
      anonymous: ~
      provider: user_db_provider
      logout:
        path: logout
      form_login:
        login_path: users
        check_path: login_check
        default_target_path: projects

  access_control:
    - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }

